# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import core_function_pb2 as core__function__pb2


class DockerCommandCallStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CommandCall = channel.unary_unary(
        '/DockerCommandCall/CommandCall',
        request_serializer=core__function__pb2.Data.SerializeToString,
        response_deserializer=core__function__pb2.Data.FromString,
        )


class DockerCommandCallServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CommandCall(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DockerCommandCallServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CommandCall': grpc.unary_unary_rpc_method_handler(
          servicer.CommandCall,
          request_deserializer=core__function__pb2.Data.FromString,
          response_serializer=core__function__pb2.Data.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'DockerCommandCall', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
