# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core_function.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='core_function.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x13\x63ore_function.proto\"-\n\x08\x46ileInfo\x12\x0f\n\x07\x66iledir\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"\x15\n\x06Result\x12\x0b\n\x03res\x18\x01 \x01(\t\"g\n\tMysqlInfo\x12\x10\n\x08\x64\x61tabase\x18\x01 \x01(\t\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0c\n\x04host\x18\x04 \x01(\t\x12\x0c\n\x04port\x18\x05 \x01(\x05\x12\x0c\n\x04\x64\x61ys\x18\x06 \x01(\x05\"\n\n\x08Nonetype2>\n\x10\x44\x61taxCommandCall\x12*\n\x12\x64\x61tax_command_call\x12\t.FileInfo\x1a\x07.Result\"\x00\x32G\n\x14MysqlDumpCommandCall\x12/\n\x16mysqldump_command_call\x12\n.MysqlInfo\x1a\x07.Result\"\x00\x32\x82\x01\n\x14PiecesDefectsProcess\x12\x35\n\x1dpieces_defects_ftp_downloader\x12\t.Nonetype\x1a\x07.Result\"\x00\x12\x33\n\x1bpieces_defects_main_process\x12\t.Nonetype\x1a\x07.Result\"\x00\x62\x06proto3')
)




_FILEINFO = _descriptor.Descriptor(
  name='FileInfo',
  full_name='FileInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filedir', full_name='FileInfo.filedir', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filename', full_name='FileInfo.filename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=68,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='Result.res', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=91,
)


_MYSQLINFO = _descriptor.Descriptor(
  name='MysqlInfo',
  full_name='MysqlInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='database', full_name='MysqlInfo.database', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='MysqlInfo.user', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='MysqlInfo.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='host', full_name='MysqlInfo.host', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='MysqlInfo.port', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='days', full_name='MysqlInfo.days', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=196,
)


_NONETYPE = _descriptor.Descriptor(
  name='Nonetype',
  full_name='Nonetype',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=208,
)

DESCRIPTOR.message_types_by_name['FileInfo'] = _FILEINFO
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.message_types_by_name['MysqlInfo'] = _MYSQLINFO
DESCRIPTOR.message_types_by_name['Nonetype'] = _NONETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileInfo = _reflection.GeneratedProtocolMessageType('FileInfo', (_message.Message,), dict(
  DESCRIPTOR = _FILEINFO,
  __module__ = 'core_function_pb2'
  # @@protoc_insertion_point(class_scope:FileInfo)
  ))
_sym_db.RegisterMessage(FileInfo)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'core_function_pb2'
  # @@protoc_insertion_point(class_scope:Result)
  ))
_sym_db.RegisterMessage(Result)

MysqlInfo = _reflection.GeneratedProtocolMessageType('MysqlInfo', (_message.Message,), dict(
  DESCRIPTOR = _MYSQLINFO,
  __module__ = 'core_function_pb2'
  # @@protoc_insertion_point(class_scope:MysqlInfo)
  ))
_sym_db.RegisterMessage(MysqlInfo)

Nonetype = _reflection.GeneratedProtocolMessageType('Nonetype', (_message.Message,), dict(
  DESCRIPTOR = _NONETYPE,
  __module__ = 'core_function_pb2'
  # @@protoc_insertion_point(class_scope:Nonetype)
  ))
_sym_db.RegisterMessage(Nonetype)



_DATAXCOMMANDCALL = _descriptor.ServiceDescriptor(
  name='DataxCommandCall',
  full_name='DataxCommandCall',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=210,
  serialized_end=272,
  methods=[
  _descriptor.MethodDescriptor(
    name='datax_command_call',
    full_name='DataxCommandCall.datax_command_call',
    index=0,
    containing_service=None,
    input_type=_FILEINFO,
    output_type=_RESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATAXCOMMANDCALL)

DESCRIPTOR.services_by_name['DataxCommandCall'] = _DATAXCOMMANDCALL


_MYSQLDUMPCOMMANDCALL = _descriptor.ServiceDescriptor(
  name='MysqlDumpCommandCall',
  full_name='MysqlDumpCommandCall',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=274,
  serialized_end=345,
  methods=[
  _descriptor.MethodDescriptor(
    name='mysqldump_command_call',
    full_name='MysqlDumpCommandCall.mysqldump_command_call',
    index=0,
    containing_service=None,
    input_type=_MYSQLINFO,
    output_type=_RESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MYSQLDUMPCOMMANDCALL)

DESCRIPTOR.services_by_name['MysqlDumpCommandCall'] = _MYSQLDUMPCOMMANDCALL


_PIECESDEFECTSPROCESS = _descriptor.ServiceDescriptor(
  name='PiecesDefectsProcess',
  full_name='PiecesDefectsProcess',
  file=DESCRIPTOR,
  index=2,
  options=None,
  serialized_start=348,
  serialized_end=478,
  methods=[
  _descriptor.MethodDescriptor(
    name='pieces_defects_ftp_downloader',
    full_name='PiecesDefectsProcess.pieces_defects_ftp_downloader',
    index=0,
    containing_service=None,
    input_type=_NONETYPE,
    output_type=_RESULT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='pieces_defects_main_process',
    full_name='PiecesDefectsProcess.pieces_defects_main_process',
    index=1,
    containing_service=None,
    input_type=_NONETYPE,
    output_type=_RESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PIECESDEFECTSPROCESS)

DESCRIPTOR.services_by_name['PiecesDefectsProcess'] = _PIECESDEFECTSPROCESS

# @@protoc_insertion_point(module_scope)
